substitutions:
  _SERVICE_NAME: program-editor
  _REGION: us-central1
  _AR_REPO: cloud-run
  _GCS_BUCKET: "app_release_bucket"   # ← replace with your bucket name
  _GCS_PREFIX: program_editor
  _RUN_SERVICE_ACCOUNT: "program-editor@mviis-docker.iam.gserviceaccount.com"

steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud artifacts repositories describe ${_AR_REPO} \
          --location=${_REGION} >/dev/null 2>&1 || \
        gcloud artifacts repositories create ${_AR_REPO} \
          --repository-format=docker \
          --location=${_REGION} \
          --description="Docker repository for Cloud Run deployments"
    env:
      - MONGODB_URI=mongodb+srv://mviis_admin:d5uNysSB0uiYT3pK@mviis.bbuf8.mongodb.net/myFirstDatabase?retryWrites=true
      - MONGODB_DB_NAME=program_editor
      - DEFAULT_SUPER_ADMIN_USERNAME=mviis
      - DEFAULT_SUPER_ADMIN_PASSWORD=mviis

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$COMMIT_SHA

  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$COMMIT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --min-instances=1
      - --service-account
      - ${_RUN_SERVICE_ACCOUNT}
      - --set-env-vars
      - MONGODB_URI=mongodb+srv://mviis_admin:d5uNysSB0uiYT3pK@mviis.bbuf8.mongodb.net/myFirstDatabase?retryWrites=true,MONGODB_DB_NAME=program_editor,DEFAULT_SUPER_ADMIN_USERNAME=mviis,DEFAULT_SUPER_ADMIN_PASSWORD=mviis,GCS_BUCKET_NAME=${_GCS_BUCKET},GCS_PREFIX=${_GCS_PREFIX}

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$COMMIT_SHA
